---
# handlers file for waves
- name: Restart docker-compose
  docker_compose:
    project_src: /docker/{{ PROJECT }}/
    restarted: true
    state: present
    pull: yes
  ignore_errors: yes
  tags:
    - waves
    - waves.config


