    - name: Copy repo file
      copy:
           src: "{{ role_path }}/files/docker-ce.repo"
           dest: /etc/yum.repos.d/docker-ce.repo
           mode: 0644
           owner: root
           group: root
      tags:
         - docker

    - name: install epel
      yum:
        name: epel-release
      tags:
          - docker

    - name: Install packet
      ignore_errors: no
      yum:
        name: ['docker-ce-20.10.6-3.el7', 'docker-ce-cli', 'containerd.io','python3-pip']
        state: present
      tags:
         - docker

    - name: Ensure Docker is started and enabled at boot.
      service:
        name: docker
        state: "{{ docker_service_state }}"
        enabled: "{{ docker_service_enabled }}"
      tags:
          - docker

    - name: Add daemon.json
      template:
        src: "{{ role_path }}/files/daemon.json"
        dest: /etc/docker/daemon.json
      tags: 
        - docker
        - docker.config
      notify:
           - Restart Docker

    - name: "Install packet executable pip"
      pip:
         name: '{{ item }}'
         executable: pip3
      loop:
#          - docker-compose~=1.23.2
          - docker-pretty-ps
      tags:
          - docker


    - meta: flush_handlers
