- name: Docker Create Net Apps
  docker_network:
        name: "{{ item }}"
#  raw: docker network create "{{ item }}"
  loop: "{{ docker_networks }}"
#  run_once: True
  ignore_errors: yes
  tags:
    - docker
    - docker_network